create url,views
osadolortech/instagram_clone pull request #4
Opened 2022-08-30 16:46 UTC by osadolortech

2022-08-31 08:08 UTC, iamr0b0tx requested changes

2022-08-31 08:08 UTC, iamr0b0tx commented on instagram_clone/settings.py
> +    'USER_DETAILS_SERIALIZER': 'user.serializers.CustomeUser',
See spelling

2022-08-31 08:08 UTC, iamr0b0tx commented on instagramapi/permision.py
> +
Not a very good name

2022-08-31 13:09 UTC, iamr0b0tx requested changes
I will not be available to review PRs anymore. You will need to move on without my reviews from here on out

2022-08-31 13:09 UTC, iamr0b0tx commented on instagramapi/serialzers.py
> +class InstapostSrilaizers(serializers.ModelSerializer):
spelling

2022-08-31 13:09 UTC, iamr0b0tx commented on instagramapi/userpermission.py
> +class CustomPermission(BasePermission):
not very descriptive name

2022-08-31 13:10 UTC, iamr0b0tx requested changes
I will not be available to review PRs anymore. You will need to move on without my reviews from here on out

2022-09-01 08:31 UTC, osadolortech commented on instagramapi/serialzers.py
> +class InstapostSrilaizers(serializers.ModelSerializer):
OK SIR THANK YOU FOR EVERYTHING

2022-09-02 12:22 UTC, merged